# Generated by Django 3.2.9 on 2021-11-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Chat ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='User ID'),
        ),
    ]
