# Generated by Django 3.2.9 on 2021-11-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20211105_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='phone',
            field=models.CharField(default='None', max_length=25, verbose_name='Номкр телефона'),
        ),
    ]
