# Generated by Django 3.2.9 on 2021-11-05 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_payment_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='complite_tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='complite_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Complite users'),
        ),
        migrations.AlterField(
            model_name='task',
            name='bon',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма для выполнения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
